Added pulsar Job support
ns1/ns1-go pull request #140
Opened 2021-08-20 17:40 UTC by ThiagoYU

2021-08-25 15:16 UTC, Zach-Johnson requested changes
few minor things noted.

2021-08-25 15:16 UTC, Zach-Johnson commented on rest/pulsar_job.go
> +			}
noted this question on the other pulsar PR as well, is there not a 404 status code or something to check instead of a hard coded string?

2021-08-25 15:16 UTC, Zach-Johnson commented on rest/pulsar_job.go
> +
remove whitespace, usually there is no whitespace between `err := .... ` and where the err is checked

2021-08-25 15:16 UTC, Zach-Johnson commented on rest/pulsar_job.go
> +			job_not_found := fmt.Sprintf("pulsar job %s not found for appid %s", jobId, appId)
no underscores in vars, lets rename this `jobNotFound`

2021-08-25 15:16 UTC, Zach-Johnson commented on rest/pulsar_job.go
> +	req, err := s.client.NewRequest("PUT", path, &j)
no need to take the address of `j` here, it is already passed in as a pointer

2021-08-25 15:16 UTC, Zach-Johnson commented on rest/pulsar_job.go
> +	resp, err := s.client.Do(req, &j)
same as above

2021-08-25 15:16 UTC, Zach-Johnson commented on rest/pulsar_job.go
> +	req, err := s.client.NewRequest("POST", path, &j)
same thing about taking the address of `j`

2021-08-25 15:16 UTC, Zach-Johnson commented on rest/pulsar_job.go
> +	resp, err := s.client.Do(req, &j)
same

2021-08-25 15:16 UTC, Zach-Johnson commented on rest/pulsar_job.go
> +			job_not_found := fmt.Sprintf("pulsar job %s not found for appid %s", j.JobID, j.AppID)
same thing on the var name

2021-08-25 15:16 UTC, Zach-Johnson commented on rest/pulsar_job.go
> +			job_not_found := fmt.Sprintf("pulsar job %s not found for appid %s", pulsarJob.JobID, pulsarJob.AppID)
same

2021-08-31 18:49 UTC, Zach-Johnson approved these changes
lgtm!

2021-08-31 19:48 UTC, mvkushnir approved these changes

2021-08-31 19:51 UTC, merged