DAITDS-231 - Develop TSIG support in Go SDK
ns1/ns1-go pull request #145
Opened 2021-09-30 19:40 UTC by ThiagoYU

2021-10-07 22:20 UTC, Zach-Johnson requested changes
Looks good, just a few clean up things.

2021-10-07 22:20 UTC, Zach-Johnson commented on rest/model/dns/tsig_key.go
> +type Tsig_key struct {
No underscores in var/struct names in Go - lets make this `TSIGKey`

2021-10-07 22:20 UTC, Zach-Johnson commented on rest/model/dns/tsig_key.go
> +// Zone wraps an NS1 /zone resource
Fix comment

2021-10-07 22:20 UTC, Zach-Johnson commented on rest/model/dns/tsig_key.go
> +// NewTSIGKey takes a name, algorithm and secret and creates a new zone.
Fix comment

2021-10-07 22:20 UTC, Zach-Johnson commented on rest/tsig_key.go
> +
remove extra line

2021-10-07 22:20 UTC, Zach-Johnson commented on rest/tsig_key.go
> +			}
can we check for a 404 status code on this instead?

2021-10-07 22:20 UTC, Zach-Johnson commented on rest/tsig_key.go
> +			}
Is there a status code for this error that we could check for instead?

2021-10-07 22:20 UTC, Zach-Johnson commented on rest/tsig_key.go
> +			}
can we check for 404 status code on this?

2021-10-07 22:20 UTC, Zach-Johnson commented on rest/tsig_key.go
> +			}
can we check for 404 status code on this?

2021-10-08 12:37 UTC, dmavrommatis commented on rest/model/dns/tsig_jey_test.go
> +package dns
name of the file has a typo

2021-10-08 12:39 UTC, dmavrommatis requested changes
can you please run staticcheck for your changes to see lint issues?

2021-10-20 16:34 UTC, Zach-Johnson requested changes

2021-10-20 16:34 UTC, Zach-Johnson commented on rest/tsig_key.go
> +	AlreadyExistsStatusCode = 409
Please use the existing constants in stdlib, they are in the http package. e.g. `http.StatusNotFound`

2021-10-20 16:34 UTC, Zach-Johnson commented on rest/tsig_key.go
> +	ErrTsigBadRequest = errors.New("bad request error, expected in S1 (18/10/2021)")
Let's just return the standard error for a bad request, we don't need to expose this.

2021-10-20 16:34 UTC, Zach-Johnson commented on rest/model/dns/tsig_key.go
> +	tsig_key := TSIGKey{
No underscores in var names. Please run a go linter on this code, it should point out stuff like this.

2021-10-20 16:34 UTC, Zach-Johnson commented on rest/tsig_key.go
> +// Update takes a *Tsug_key and modifies basic details of a TSIG key.
typo `Tsug_key`

2021-10-27 14:50 UTC, Zach-Johnson requested changes

2021-10-27 14:50 UTC, Zach-Johnson commented on rest/tsig_key.go
> +	ErrTsigBadRequest = errors.New("bad request error, expected in S1 (18/10/2021)")
@ThiagoYU this comment is unresolved still

2021-10-27 16:18 UTC, ThiagoYU commented on rest/tsig_key.go
> +	ErrTsigBadRequest = errors.New("bad request error, expected in S1 (18/10/2021)")
@Zach-Johnson Sorry for this... Just fixed

2022-02-24 19:34 UTC, pcatalini approved these changes
LGTM

2022-02-25 15:36 UTC, Zach-Johnson approved these changes

2022-02-25 15:37 UTC, merged