DAITDS-240 - DNS View added
ns1/ns1-go pull request #147
Opened 2021-10-19 19:04 UTC by ThiagoYU

2021-10-27 15:05 UTC, Zach-Johnson requested changes
small cleanup requests

2021-10-27 15:05 UTC, Zach-Johnson commented on rest/model/dns/dns_view.go
> +func NewDNSView(view_name string) *DNSView {
no underscores in var names

2021-10-27 15:05 UTC, Zach-Johnson commented on rest/dns_view.go
> +func (s *DNSViewService) Get(view_name string) (*dns.DNSView, *http.Response, error) {
no underscores in var names

2021-10-27 15:05 UTC, Zach-Johnson commented on rest/dns_view.go
> +func (s *DNSViewService) Delete(view_name string) (*http.Response, error) {
no underscores in var names

2021-10-27 15:05 UTC, Zach-Johnson commented on rest/dns_view.go
> +	m_updated := make(map[string]int)
no underscores in var names

2022-10-26 19:16 UTC, eravin-ns1 commented
This code was merged in #171

2022-10-26 19:16 UTC, closed without merging