DAITDS-247 - Added defaultPermissions function
ns1/ns1-go pull request #148
Opened 2021-10-26 17:41 UTC by ThiagoYU

2021-10-27 15:32 UTC, Zach-Johnson requested changes
@ThiagoYU the permissions piece of this looks good, I had just a couple of small comments.

On the duplication for the user/team/apikey objects, I'm wondering if we can do something different to avoid this much duplication. Do you think we could put the PermissionsMapV2 on the v1 structs for user/team/apikey as a pointer and then use a custom json marshaler to choose which permission struct to use? So basically, if the PermissionsMapV2 != nil, then use that, otherwise use the original. I _think_ this could work, and would remove a lot of the duplication. What do you think?

2021-10-27 15:32 UTC, Zach-Johnson commented on rest/account_apikey_v2.go
> +			if err.(*Error).Message == "unknown api key" {
``` suggestion
		switch e := err.(type) {
		case *Error:
			if e.Message == "unknown api key" {
```

2021-10-27 15:32 UTC, Zach-Johnson commented on rest/account_apikey_v2.go
> +// )
lets just delete this stuff then

2021-10-27 15:32 UTC, Zach-Johnson commented on rest/model/account/permissions_v2.go
> +// }
lets delete this

2022-02-04 17:42 UTC, ThiagoYU commented
This seems to be fixed

2022-02-04 17:42 UTC, closed without merging