INBOX-1443
ns1/ns1-go pull request #154
Opened 2022-01-14 13:02 UTC by ThiagoYU

Fixed record creation bug described in [INBOX-1443](https://ns1inc.atlassian.net/browse/INBOX-1443)

2022-01-14 18:49 UTC, Zach-Johnson requested changes
Needs a test

2022-01-14 18:49 UTC, Zach-Johnson commented on rest/model/data/meta.go
> +				}
can we add a test for this case?

2022-01-14 18:54 UTC, ponbiki submitted a review, later dismissed
LGTM (just see Zach's comment regarding tests)

2022-01-14 19:52 UTC, Zach-Johnson approved these changes

2022-01-14 21:45 UTC, Zach-Johnson commented
@ThiagoYU I'm getting test failures when I run the tests for this locally, I think they are unrelated though. We should fix them in a separate PR I think?

```rest/model/pulsar/pulsar_job_test.go:9:6: TestNewBBPulsarJob redeclared in this block
	/Users/zachjohnson/w/ns1/opensource/ns1-go/rest/model/pulsar/application_test.go:8:28: previous declaration
ok  	gopkg.in/ns1/ns1-go.v2/mockns1	0.451s
--- FAIL: TestApplication (0.00s)
    --- FAIL: TestApplication/Get (0.00s)
        --- FAIL: TestApplication/Get/Error (0.00s)
            --- FAIL: TestApplication/Get/Error/HTTP (0.00s)
                application_test.go:107:
                    	Error Trace:	application_test.go:107
                    	Error:      	"application does not exist" does not contain "test error"
                    	Test:       	TestApplication/Get/Error/HTTP
--- FAIL: TestPulsarJob (0.00s)
    --- FAIL: TestPulsarJob/List (0.00s)
        --- FAIL: TestPulsarJob/List/Error (0.00s)
            --- FAIL: TestPulsarJob/List/Error/Other_errors (0.00s)
                pulsar_job_test.go:95:
                    	Error Trace:	pulsar_job_test.go:95
                    	Error:      	"pulsar application does not exist" does not contain "test error"
                    	Test:       	TestPulsarJob/List/Error/Other_errors
FAIL
FAIL	gopkg.in/ns1/ns1-go.v2/rest	0.357s
```

2022-01-17 11:39 UTC, ThiagoYU commented
> 

Yes @Zach-Johnson 
This is unrelated, we can take a look at this in other PR.

2022-01-18 16:37 UTC, merged