feat: add search api endpoint
ns1/ns1-go pull request #194
Opened 2023-02-16 12:08 UTC by fgouteroux

Hello,

I would add the search api endpoint, it could be useful for [terraform-provider-ns1](https://github.com/ns1-terraform/terraform-provider-ns1) to perform some additional validations.

2023-03-03 14:36 UTC, fgouteroux commented
Hello, any updates, review ?

2023-03-21 18:33 UTC, dmavrommatis requested changes
Some small changes and it should be good to go!

2023-03-21 18:33 UTC, dmavrommatis commented on rest/search.go
> +func (s *RecordSearchService) Find(params string) (*dns.SearchResult, *http.Response, error) {
```suggestion
func (s *RecordSearchService) Search(params string) (*dns.SearchResult, *http.Response, error) {
```

2023-03-21 18:33 UTC, dmavrommatis commented on rest/search.go
> +func (s *ZoneSearchService) Find(params string) (*dns.SearchResult, *http.Response, error) {
```suggestion
func (s *ZoneSearchService) Search(params string) (*dns.SearchResult, *http.Response, error) {
```

2023-03-23 11:43 UTC, dmavrommatis approved these changes
LGTM :tada:

2023-03-28 21:09 UTC, ponbiki approved these changes

2023-04-27 17:30 UTC, fgouteroux commented
Hello, still not merged ?

2023-04-28 11:50 UTC, merged