INBOX-344: make pagination match standard behavior a bit more
ns1/ns1-go pull request #77
Opened 2019-10-25 21:16 UTC by rupa

On HTTP error, the Do handler returns the response as well as the
error, and people were using that. In lieu of a breaking change,
we emulate this behavior as closely as we can in DoWithPagination.

DoWithPagination:
  * Return the response as well as the error, on HTTP Error
  * We now clobber the old responses as we traverse pages. On HTTP
    error, the response will match the error. Without error, the
    response will be the _last_ page of results.

Tried to exercise this in unit tests. Since it's a bit subtle, it
would be nice if a test broke if we accidentally change behavior.

Also:
  * Refactored the little "mockAPI" stuff for more generic use
  * Add a litle unit test for the hearer parsing funcs

2019-10-28 15:28 UTC, mburtless requested changes
Looks good, only tiny thing would be that I think we should just be more explicit about calling out and testing the one scenario when resp may be `nil`, since that's no longer obvious from `DoWithPagination()`.

Also, it would be great to ~use `assert.Equalf()` and~ (forgot `Equal` supports this out of the box) get `msg`s added to the assert statements, since these test funcs have multiple tests enclosed and I don't think some of what we are testing would be very clear on failure.  I think it's totally fine if we want to tackle that in another PR though.

2019-10-28 15:28 UTC, mburtless commented on rest/client.go
> +// responded with a non-2XX status.
I think it would be worth it to explicitly call out that `resp` may be `nil` (i.e. if `Do` has an error making the actual request) as this code hides that possibility.

I see you're calling that out in `getURI`, but I think we should make this more obvious here, where users are more likely to see it.

2019-10-28 15:28 UTC, mburtless commented on rest/zone_test.go
> +	assert.Nil(t, err)
FYI in case you haven't seen it, there's `assert.NoError()` which is essentially the same, but just a little more explicit when read.  The `if assert.NoError(t, err) { //some other enclosed tests }` pattern may be more readable here.

2019-10-28 15:28 UTC, mburtless commented on rest/zone_test.go
> +func TestZone_http_errors(t *testing.T) {
I think one failure scenario is untested here: when `c.httpClient.Do(req)` in `Do` returns `err`.  This should return a nil `resp`.  Not a HTTP error, of course, so maybe it belongs in it's own test.

2019-10-28 17:25 UTC, rupa commented on rest/client.go
> +// responded with a non-2XX status.
done, and noted in docstring for `Do` as well

2019-10-28 17:25 UTC, rupa commented on rest/zone_test.go
> +	assert.Nil(t, err)
nice, done

2019-10-28 17:29 UTC, rupa commented on rest/zone_test.go
> +func TestZone_http_errors(t *testing.T) {
yeah, that's what I was having trouble thinking of how to test. Agree it should be a separate test. I came up with something, lets see if it feels reasonable to you.

2019-10-28 19:14 UTC, mburtless requested changes
I think what you have is the correct solution for testing `Zones.List()`.

I failed at mentioning this earlier, but after thinking about this it occurs to me that we probably also want unit test coverage of `DoWithPagination()` and `getURI()` directly in `client_test.go`, right?  The coverage now seems closer to integration tests of `Zones.List()` and `Zones.Get()`.

Edit - One other piece of feedback that just occurred to me:  the naming scheme for these test functions seems strange to me.  I think what you typically see is `TestMyFunc` or `TestMyPackage_MyFuncSpecificBehaviour`, but it looks like the code switches to snake case for the piece that denotes the function and behavior we are testing.  Mixing case in function names seems like an antipattern.

I think the test functions that test multiple functions should also be broken up.  Functions and tests are usually one to one, in that a single test tests a single function.

2019-10-28 19:50 UTC, mburtless commented on rest/zone_test.go
> +func TestZone_list_pagination(t *testing.T) {
Snake case function names is weird.  Should probably be named `TestZone_ListPagination`

2019-10-28 19:51 UTC, mburtless commented on rest/zone_test.go
> +func TestZone_get_pagination(t *testing.T) {
Should probably be named `TestZone_GetPagination`

2019-10-28 19:52 UTC, mburtless commented on rest/zone_test.go
> +func TestZone_pagination_disabled(t *testing.T) {
Should be named `TestZone_PaginationDisabled`

2019-10-28 19:55 UTC, mburtless commented on rest/zone_test.go
> +func TestZone_http_errors(t *testing.T) {
Should be split into two functions and named something like `TestZone_ListHTTPErrors` and `TestZone_ListHTTPErrors`

2019-10-29 17:54 UTC, mburtless approved these changes
LGTM 🚀 

I'll just note that some of these tests seem like a good fit for table driven test pattern, but seems like a low priority to compared to getting this fix in.

2019-10-29 18:53 UTC, merged