DDI Permissions
ns1/ns1-go pull request #89
Opened 2020-01-08 16:59 UTC by Zach-Johnson

I tested this locally against managed and private and looks good to me. I also tested it against the private demo account, and it's failing because the demo is running an older version (2.1.1) and the permission for `security.manage_active_directory` isn't in the schema until I think 2.2.1. I'm thinking we should keep this as-is though, I don't want to remove it and then have to re-add it and maintain compatibility for both.

2020-01-08 19:21 UTC, mburtless requested changes
LGTM, just one question on `PermissionsSecurity`.

2020-01-08 19:21 UTC, mburtless commented on rest/model/account/permissions.go
> +	ManageActiveDirectory bool `json:"manage_active_directory,omitempty"`
Why not make this field's type `*bool` and get rid of `permissionsDDISecurity`?

2020-01-08 19:31 UTC, mburtless approved these changes
LGTM 🌭

2020-01-09 19:05 UTC, merged

2020-01-13 17:17 UTC, dwhittle-sfdc commented
@Zach-Johnson @mburtless 
Using this updated version against v2.2.1 of the DDI product it is still not working for me:

`2020/01/13 12:08:06 ERROR: Unable to manage team configuration: PUT https://localhost/v1/account/teams: 400 Input validation failed (Unknown properties for field "permissions": "monitoring")`

The issue appears that the `monitoring` permissions are still being bundled into the JSON object and the API does not like that it is included since monitoring options are not currently available for the DDI product.

Here is a simplified version of what I am doing:

```go
t = &account.Team{Name: team.Name}
t.Permissions.DNS.ZonesAllow = []string{}
t.Permissions.DNS.ZonesDeny = []string{}
t.Permissions.DHCP = new(account.PermissionsDHCP)
t.Permissions.IPAM = new(account.PermissionsIPAM)
t.Permissions.Security = new(account.PermissionsSecurity)

// ... Note: I never touch t.Permissions.Monitoring

_, err = ns1.Teams.Create(t)
```

2020-01-13 17:26 UTC, Zach-Johnson commented
Hi @dwhittle-sfdc,

An additional `DDI` setting was added to the configuration for the client. You can set it like this:
```
client := api.NewClient(httpClient, api.SetAPIKey(apiKey), api.SetDDIAPI())
```
This should enable DDI support, and swap what permissions get bundled into the JSON object. If you hadn't already set that configuration option, can you try that?

We should probably clarify in the documentation that this needs to be set explicitly.

2020-01-13 17:36 UTC, dwhittle-sfdc commented
@Zach-Johnson That got it, at least for the `Team` object. I still have to use custom `User` and `APIKey` objects due to other fields I need that are not yet supported in the package (`invite_token` for `User`, and `ip_whitelist` for `APIKey`). I'll have to update my custom code to act like the package is now doing. Thanks

2020-01-13 19:46 UTC, Zach-Johnson commented
Glad that fixed it. Thanks for the heads up on some of those unsupported fields - I've added a ticket to our backlog to add support for missing fields and it should be prioritized soon.